- name: Send request to API (list EIP)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/publicips"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: floatingiplist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: floatingiplist.status == 200
  changed_when: false

- debug:
    msg: "{{  floatingiplist.json }}"
