- name: Send request to API (list subnet for lookup)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/subnets"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: subnet_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: subnet_result.status == 200
  changed_when: false
  when:
    - subnet_name is defined

- name: Set fact for subnet_id if subnet_name is defined
  set_fact:
    subnet_id: "{{ (subnet_result.content|from_json)|json_query(\"subnets[?name=='\" + subnet_name + \"'].id|[0]\") }}"
  when:
    - subnet_name is defined and subnet_name|length != 0

# duplicated code
- name: Send request to API (list VPC for lookup)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/vpcs"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: vpc_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: vpc_result.status == 200
  changed_when: false
  when:
    - vpc_name is defined

- name: Set fact vpc_id if vpc_name is defined
  set_fact:
    vpc_id: "{{ (vpc_result.content|from_json)|json_query(\"vpcs[?name=='\" + vpc_name + \"'].id|[0]\") }}"
  when:
    - vpc_name is defined
