- name: Send request to API (list keypair)
  uri:
    url: "{{ AUTH_URL_ECS }}/os-keypairs"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: keypairlist_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: keypairlist_result.status == 200
  changed_when: false
  when:
    - ecs_adminkey is defined

- name: Set fact ecs_adminkey_name if ecs_adminkey is defined
  set_fact:
    ecs_adminkey_name: "{{ (keypairlist_result.content|from_json)|json_query(\"keypairs[?keypair.name=='\" + ecs_adminkey + \"'].keypair.name\") }}"
  when:
    - ecs_adminkey is defined and ecs_adminkey|length != 0
