- name: Send request to API (list public zone)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones?type=public"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: zonelist_public

- name: Send request to API (list private zones)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones?type=private"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: zonelist_private

- name: Set fact zonelist
  set_fact:
    zonelist: "{{ zonelist_public.json.zones }} + {{ zonelist_private.json.zones }}"

- name: List zones
  debug: 
    msg: "{{ zonelist }}"
  when: zonelist is defined
