- name: reform certificate
  shell: awk '$1=$1' ORS='\\n' {{ elb_certificate_certificate_file }}
  register: elb_certificate_certificate

- name: reform certificate key
  shell: awk '$1=$1' ORS='\\n' {{ elb_certificate_key_file }}
  register: elb_certificate_key

- name: Get elb_certificate_id
  include: certificatelookup.yml

- name: Send request to API (Create ELB Certificate)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/certificate"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'certificatecreate.json.j2')|to_json }}"
  register: elbcertificate
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elbcertificate.status == 200
  changed_when: false
  when:
    - not elb_certificate_id or elb_certificate_id is undefined

- debug:
    msg: "{{ elbcertificate }}"
