#- name: Lookup elb_id
#  include: lookup.yml

- name: Send request to API (delete ELB)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/loadbalancers/{{ elb_id }}"
    method: DELETE
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elb
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elb.status == 200
  changed_when: false

- debug:
    msg: "{{ elb }}"
