- name: Send request to API (list ELB)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/loadbalancers"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elblist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elblist.status == 200
  changed_when: false

- debug:
    msg: "{{ elblist }}"
